---

- hosts: localhost
  become: yes
  become_user: root
  tasks: 
  
  - name: Check postgresql-11.service status
    systemd: state=started name=postgresql-11.service

  - name: netstat
    shell: /bin/netstat -tulnp |  grep ":{{ item }} " | sed -e 's/.*\///'
    register:
      netstat_result
    with_items:	
      - 5432
    changed_when: false

  - name: print result
    debug:
      msg: "for port: {{ item.item }}, netstat stdout was: {{ item.stdout }}"
    with_items:
    - "{{ netstat_result.results }}"

