---
 - hosts: localhost
   become: yes
   become_user: root
   tasks:
    - name: Verify postgresql.conf listen_address
      lineinfile:
        path: /var/lib/pgsql/11/data/postgresql.conf
        regex: "^(.*)#listen_addresses = 'localhost(.*)$"
        line: "listen_addresses = '*'"
        backup: yes
 
    - name: Verify postgresql.conf port 5432
      replace: 
        path: /var/lib/pgsql/11/data/postgresql.conf
        regexp: '#port = 5432'
        replace: 'port = 5432'
        backup: yes
   
#    - name: Verify postgresql.conf port 5432
#      lineinfile:
#        path: /var/lib/pgsql/11/data/postgresql.conf
#        regex: "^(.*)#port=5432(.*)$"
#        line: "port = 5432"
#        backup: yes

